tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up -d --build --force-recreate --no-deps
ports:
  - port: 3000
    onOpen: open-browser
    
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    
