---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - formulahendry.auto-close-tag
    - redwan-hossain.auto-rename-tag-clone
    - alefragnani.bookmarks
    - hansuxdev.bootstrap5-snippets
    - mikestead.dotenv
