version: "3"
services:
  app:
    container_name: my-node-app
    image: "node:14.18.1-bullseye"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 3002:3002
    command: ["tail", "-f", "/dev/null"] 
    extra_hosts:
      - "host.docker.internal: 172.17.0.1"
     